apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-banka-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ingress.class: "nginx"  # Spécifie le contrôleur Nginx
spec:
  rules:
    - host: api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-banka
                port:
                  number: 8080  # Port du service backend

